### PR TITLE
Refactor code 

### PR DESCRIPTION
**Pull request by AUsfy**
Hello Gary,

Thanks for the solution. I was curious about how it works, so I delved deep into the code. Along the way, I also made some code improvements and refactoring which I'm suggesting here. 

This PR:
- Removes deprecated collections usage (HashTable, ArrayList)
- Refactor code  

I tested the changes on my subscription and they look good

### CODE REVIEW

**Comment by gamullen** [comment]
I'll consider it if you change back conditional tests to have the null parameter first. It's how I've been coding for decades. For example, "if (null == myVar)." It avoids accidentally doing "if (myVar = null)," which back in the day with Java would compile and produce unexpected results.

**Comment by AUsfy** [comment]
I understand, actually in C# it's different it won't compile if you do "if (myVar = null)" , the condition must be a Boolean. 
For example, for the previous expression (myVar = null) if my myVar is a string, the expression will evaluate to a string which won't work for the condition.
Additionally, in C# we usually write variables checks this way, it's the common usage

**Comment by gamullen** [comment]
Yup, I know. But it's my coding style, no reason to change.

**Comment by AUsfy** [comment]
Ah I got it, I'll make the necessary changes then.

**Comment by gamullen** [comment]
Thanks. I know it's kinda dumb, but it wouldn't be my handwriting anymore! Appreciate your help!

**Review by gamullen — APPROVED** [review]

**Comment by AUsfy** [comment]
By the way, I had a better grasp of your coding style after discussion which made more sense than the first time I worked with the code.
I'm happy to help with any future updates or fixes.
Thanks

**Pull request merged**
